CREATE OR REPLACE VIEW `delivery_zone.vw_ordem_origem` (
    ID_Access                   OPTIONS(description="Identificador do Acesso, código do cliente - serviceId."),
    ID_Order                    OPTIONS(description="Identificador da Ordem."),
    ID_External                 OPTIONS(description="Identificador externo do endereço."),
    ID_Correlation              OPTIONS(description="Identificador da Correlação utilizado pelo Tenant responsavel pelo vinculo da camada de ordem do Tenant com a FiBrasil (opcional)."),
    ID_Workflow                 OPTIONS(description="Identificador do Workflow do FullfilmentOne."),
    ID_Char_Reserve             OPTIONS(description="Identificador da Reserva."),
    Sk_Access_Reserve           OPTIONS(description="Campo concatenado: 'ID_Access' + 'ID_Reserva'."),
    IN_State                    OPTIONS(description="Indicador do Estado da Ordem, Ex: Completed, Failed, Cancelled. - internal.orderProcesses.state."),
    IN_Service_Provider         OPTIONS(description="Nome do Tenant responsavel pelo serviço atrelado a Ordem."),
    IN_Action                   OPTIONS(description="Ação Social da Ordem."),
    IN_Service_Specification    OPTIONS(description="Identificação da árvore de serviço do cliente reservado (básico ou avançado)."),
    IN_Status_Code              OPTIONS(description="Código de retorno (NOK ou OK)."),
    IN_Status_Message           OPTIONS(description="Mensagem de retorno da API referente a Ordem (Cancelada ou sucesso)."),
    IN_Char_Cpe_SN              OPTIONS(description="Identificação dos CPEs (Serial da identificação do equipamento)."),
    IN_Char_Cpe_Action          OPTIONS(description="Referente a tipo de ordem de adicionar ou deletar o equipamento (ADD ou DELETE)."),
    IN_Char_Cpe_Action_SWAP     OPTIONS(description="Quando ocorre troca de CPE (Obs.: Ordem de DELETE ou ADD)."),
    IN_Char_Cpe_Model           OPTIONS(description="Modelo do CPE."),
    IN_Char_Cpe_Vendor          OPTIONS(description="Fabricante da CPE."),
    IN_Char_Profile             OPTIONS(description="Perfil de Serviço com a respectiva velocidade (VOIP, IPTV, Banda larga)."),
    IN_Char_Service_State       OPTIONS(description="Identificador do estado da CPE (Ex.: Active)."),
    IN_Char_Service_Name        OPTIONS(description="Default: serviceState"),
    IN_Service_Resource          OPTIONS(description="Default: Null"),
    TS_Order_Date               OPTIONS(description="Data e Hora da Criação da Ordem"),
    TS_Start_Time               OPTIONS(description="Data e Hora de Inicio da Ordem"),
    TS_End_Time                 OPTIONS(description="Data e Hora da Conclusão da Ordem"),
    TS_Last_Update              OPTIONS(description="Data e Hora da Última Atualização da Ordem"),
    DT_FOTO                     OPTIONS(description="Data do processamento da camada geral retirada do Snapshot")
)
OPTIONS(description="Uma visão que representa as ordens. \nDomínio de Dado: Eficiência Operacional - eop \nPeríodo de retenção: a definir \nClassificação da Informação: a definir",
    labels=[("eficiencia_operacional", "eop")]
)AS SELECT
    ID_Access,
    ID_Order,
    ID_External,
    ID_Correlation,
    ID_Workflow,
    ID_Char_Reserve,
    Sk_Access_Reserve,
    IN_State,
    IN_Service_Provider,
    IN_Action,
    IN_Service_Specification ,
    IN_Status_Code,
    IN_Status_Message,
    IN_Char_Cpe_SN,
    IN_Char_Cpe_Action,
    IN_Char_Cpe_Action_SWAP,
    IN_Char_Cpe_Model,
    IN_Char_Cpe_Vendor,
    IN_Char_Profile,
    IN_Char_Service_State,
    IN_Char_Service_Name,
    IN_Service_Resource,
    TS_Order_Date,
    TS_Start_Time,
    TS_End_Time,
    TS_Last_Update ,
    DT_FOTO 
    FROM `gold_zone.tb_eop_ordem_origem` limit 19